config/routes.rb
Rails.application.routes.draw do
  resources :registered_applications
  resources :events

  root to: "welcome#index"

  devise_for :users

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
 	has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :registered_applications        
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
	before_filter :set_access_control_headers
	skip_before_action :verify_authenticity_token

	def set_access_control_headers
		headers['Access-Control-Allow-Origin'] = '*'
		headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
		headers['Access-Control-Allow-Headers'] = 'Content-Type'
	end

	def create
		registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
		if registered_application.present?
			registered_application.events.create(event_params)
		end
		head 200
	end

	def preflight
		head 200
	end

	private
	def event_params
		params.require(:event).permit(:name)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :authenticate_user!

  def new
  	@registered_application = RegisteredApplication.new
  end

  def create
  	@registered_application = RegisteredApplication.new(registered_application_params)
  	@registered_application.user = current_user

  	if @registered_application.save
  		flash[:notice] = "Registered Application was saved successfully."
  		redirect_to @registered_application
  	else
  		flash[:error] = "Registered Application failed to save."
  		render :new
  	end
  end

  def index
  	@registered_applications = current_user.registered_applications.all
  end

  def edit
  	@registered_application = RegisteredApplication.find(params[:id])
  end

  def update
  	@registered_application = RegisteredApplication.find(params[:id])

  	@registered_application.assign_attributes(registered_application_params)

  	if @registered_application.save
  		flash[:notice] = "Registered Application was updated."
  		redirect_to @registered_application
  	else
  		flash[:error] = "Error saving Registered Application. Please try again."
  		render :edit
  	end
  end

  def show
  	@registered_application = RegisteredApplication.find(params[:id])

  	@events = @registered_application.events.group_by(&:name)
  end

  def destroy
  	@registered_application = RegisteredApplication.find(params[:id])

  	if @registered_application.destroy
  		flash[:notice] = "\"#{@registered_application.name}\" was deleted successfully."
  		redirect_to action: :index
  	else
  		flash[:error] = "there was an error deleting your Registered Application."
  		render :show
  	end
  end

  private
  def registered_application_params
  	params.require(:registered_application).permit(:name, :url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag '//www.google.com/jsapi', 'chartkick' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<ul class="nav nav-tabs">
		<% if user_signed_in? %>
   	Signed in as: <strong><%= current_user.email %></strong> |
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  	<% else %>
    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
	</ul>
<div class="flash">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type= "button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type= "button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert aler-warning">
      <button type="button" class="close" data-dismiss="alert">&time;</button>
      <%= flash[:alert] %>
    </div>  
  <% end %>
</div>
</div>
<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for registered_application do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control", placeholder: "Enter Register Application name here." %>
	</div>
	<div class="form-group">
		<%= f.label :url %>
		<%= f.text_field :url, class: "form-control", placeholder: "Enter Register Application URL here." %>
	</div>
	<%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/registered_applications/edit.html.erb
<h1>Edit <%= @registered_application.name %></h1>
<div class="row">
	<div class="col-md-8">
		<%= render partial: 'form', locals:  { registered_application: @registered_application } %>
	</div>
</div>

app/views/registered_applications/index.html.erb
<h1>Registered Applications</h1>
<%= link_to "Add Application", new_registered_application_path, class: "btn btn-success" %>
<div class="row">
	<div class="col-md-8">
		<% @registered_applications.each do |registered_application| %>
			<div class="media">
				<div class="media-body">
					<h4 class="media-heading">
						<%= link_to registered_application.name, registered_application %>
					</h4>
				</div>
			</div>
		<% end %>
	</div>	
</div>

app/views/registered_applications/new.html.erb
<h1>New Registered Application</h1>
<div class="row">
	<div class="col-md-8">
		<%= render partial: 'form', locals:  { registered_application: @registered_application } %>
	</div>
</div>

app/views/registered_applications/show.html.erb
<h1><%= @registered_application.name %></h1>

<div class="row">
	<div class="col-md-8">
		<%= link_to "Edit", edit_registered_application_path(@registered_application), class: 'btn btn-success' %>
		<%= link_to "Delete Registered Application", @registered_application, method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete this application?"} %>
		<%= pie_chart @registered_application.events.group(:name).count %>
		<%= line_chart @registered_application.events.group_by_day(:created_at).count %>
	</div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>